---
- hosts: all 
  gather_facts: no
  become: yes
  tasks: 
  - name: Waiting for ssh
    wait_for_connection:
      timeout: 900
  - name: load br_netfilter
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - br_netfilter
      - overlay
  - name: iptables4/6 bridged traffic
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
    with_items:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-arptables
      - net.ipv4.ip_forward
  - name: Swap off
    shell: "swapoff -a"
  - name: Disable swap in fstab
    mount:
      name: swap
      fstype: swap
      state: absent
  - name: Setup dep key
    apt_key:
      url: "{{ item }} "
      state: present
    with_items:
      - https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - https://gvisor.dev/archive.key
      - https://aquasecurity.github.io/trivy-repo/deb/public.key
  - name: Setup K8s dep
    apt_repository:
      repo: "{{ item.repo }}"
      state: present
      filename: "{{ item.filename }}"
    with_items:
      - { repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main", filename: "kubernetes.list"}
      - { repo: "deb https://storage.googleapis.com/gvisor/releases release main", filename: "gvisor.list"}
      - { repo: "deb https://aquasecurity.github.io/trivy-repo/deb focal main"}
  - name: Update and upgrade apt
    apt:
      force_apt_get: 'yes'
      update_cache: 'yes'
      upgrade: 'yes'
  - name: Install dependencies
    apt:
      force_apt_get: yes
      pkg:
      - libseccomp2
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - curl
      - ethtool
      - kubelet={{ k8s_ver }}-00
      - kubeadm={{ k8s_ver }}-00
      - kubectl={{ k8s_ver }}-00
      - containerd
      - runsc
      - open-iscsi
      - trivy
  - name: hold kubeadm
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
      - kubelet
      - kubeadm
      - kubectl 
  - name: rook dir
    file:
      path: /var/lib/rook
      state: directory
  - name: create containerd default config
    shell: containerd config default > /etc/containerd/config.toml
  - name: config containerd config
    blockinfile:
      path: /etc/containerd/config.toml
      insertafter: EOF
      block: |
        disabled_plugins = ["restart"]
        [plugins.linux]
        shim_debug = true
        [plugins.cri.containerd.runtimes.runsc]
        runtime_type = "io.containerd.runsc.v1"
        [plugins.cri.containerd.runtimes.runsc.options]
        TypeUrl = "io.containerd.runsc.v1.options"
        ConfigPath = "/etc/containerd/runsc.toml"
  - name: config runsc config
    blockinfile:
      path: /etc/containerd/runsc.toml
      backup: yes
      block: |
        log_path = "/var/log/runsc/%ID%/shim.log"
        log_level = "debug"
        [runsc_config]
          debug = "true"
          debug-log = "/var/log/runsc/%ID%/gvisor.%COMMAND%.log"
  - name: Start containerd service 
    systemd:
      name: containerd
      state: started
      enabled: yes
  - name: harden kernel
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
    with_items:
      - kernel.modules_disabled
      - kernel.randomize_va_space
      


