apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: ssung@yugabyte.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: homelab-letsencrypt
    solvers:
    - http0:
        ingress:
          class: nginx
    - dns01:
        cloudDNS:
          project: $PROJECT_ID
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-account
            key: key.json

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home.lab
  namespace: default
spec:
  secretName: home-lab-tls
  IssuerRef:
    name: letsencrypt-staging
  dnsNames:
  - '*.home.lab'
  - home.lab